name: Validate Fastlane
on:
  push:
    branches:
      - android
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - name: Validate Fastlane Supply Metadata
        # You may pin to the exact commit or the version.
        # uses: ashutoshgngwr/validate-fastlane-supply-metadata@d03bc88bf15d7c2ef8682fa057afbf2e4bc85fb4
        uses: ashutoshgngwr/validate-fastlane-supply-metadata@v2
